from exception.error import error
__all__ = ["error"]